### ISSUE TITLE
Get Root Dir

### ISSUE THREAD

**Issue by EricDriussi** [notjedi/nvim-rooter.lua#5]
Hi there!
Not really an issue, just wondering if there would be a way to get the current root dir, or rather if there is one.

I understand that vim-rooter for example has a `FindRootDirectory()` that returns and empty string if no root dir is found.

Something like that would be nice, any idea how to achieve that?

**Comment by notjedi** [comment]
hi @EricDriussi, there is no way to get the current root directory as of now. i was looking into `vim-rooter` while implementing this plugin but i didn't find a really useful use case for `FindRootDirectory` so i really didn't add it in. now that there's an issue i might add it in. can you elaborate on your use case?

**Comment by notjedi** [comment]
@EricDriussi well i guess one can extend it any way they want to so, yeah i'll add it in once i'm done with my exams or prolly even before they are over.
